### ISSUE TITLE
Add note about cache busting

### ISSUE THREAD

**Issue by thermokarst** [qiime2/cookiecutter-plugin-template#10]
This has come up a few times on the forum, etc. When devs first get started with plugins, this seems to be a common stumbling block. We should stick some inline comments in here in a few places that remind folks to run `qiime dev refresh-cache` when necessary.

**Comment by jairideout** [comment]
👍 , it'd also be helpful to document this in the "plugin development" page: https://docs.qiime2.org/2.0.6/plugins/developing/
